FROM php:apache

RUN apt-get update && apt-get install -y zlib1g-dev libicu-dev g++ git

RUN docker-php-ext-configure intl
RUN docker-php-ext-install intl
RUN docker-php-ext-install zip

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer